version: 2
jobs:
  build-and-test:
    environment:
      CC_TEST_REPORTER_ID: 1fdf0c31ff84d92bab0610beb4ea4442153901bf3379e3241a8d80456526b89c
    docker:
      - image: circleci/php:7.1-node-browsers

    steps:
      - checkout

      - run:
          name: Install system packages
          command: sudo apt update
      - run:
          name: Install PHP extensions
          command: sudo docker-php-ext-install zip

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install Composer
          command: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter

      - run:
          name: Unit Tests
          command: |
            ./cc-test-reporter before-build
            ./vendor/bin/phpunit --configuration phpunit.xml.dist
            ./cc-test-reporter after-build --coverage-input-type clover --exit-code $?

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-and-test