version: 2
jobs:
  build-and-test:
    docker:
      - image: circleci/php:7.1-node-browsers

    steps:
      - checkout

      - run:
          name: Install system packages
          command: sudo apt update
      - run:
          name: Install PHP extensions
          command: sudo docker-php-ext-install zip

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install Composer
          command: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      - run:
          name: Unit Tests
          command: ./vendor/bin/phpunit --configuration phpunit.xml.dist

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-and-test